name: atreeon_find_replace
description: finds and replaces text in files (useful for configuring build.gradle & androidManifest.xml)
version: 0.0.1+1
homepage: https://atreeon.com
repository: https://github.com/atreeon/atreeon_find_replace
executables:
  atreeon_find_replace:

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  args: ^2.4.1
  dartx: ^0.6.0
  intl: ^0.17.0

dev_dependencies:
  test: ^1.24.2
  build_runner: ^2.3.3